import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';

const findSheetByTitle = ({
  doc,
  log,
  title,
}: {
  doc: any;
  log: (message: string) => void;
  title: string;
}): any => {
  const { sheetCount, sheetsByIndex } = doc;
  for (let i = 0; i < sheetCount; i++) {
    const currentSheet = sheetsByIndex[i];
    if (currentSheet.title === title) {
      log(`Reviewing sheet with title: ${currentSheet.title} <- SHEET FOUND`);
      return currentSheet;
    }

    log(`Reviewing sheet with title: ${currentSheet.title}`);
  }

  return null;
};

const getSpreadsheet = async ({
  googleSpreadsheetId,
  log,
  serviceAccountAuth,
  worksheetTitle,
}: {
  googleSpreadsheetId: string;
  log: (message: string) => void;
  serviceAccountAuth: JWT;
  worksheetTitle: string;
}) => {
  const doc = new GoogleSpreadsheet(googleSpreadsheetId, serviceAccountAuth);
  await doc.loadInfo();
  log(`Loaded spreadsheet: ${doc.title}`);
  const sheet = findSheetByTitle({ doc, log, title: worksheetTitle });
  if (sheet === null) {
    log(
      `Worksheet with title "${worksheetTitle}" not found in spreadsheet "${doc.title}"`,
    );
  }

  return sheet;
};

interface SpreadsheetOptions {
  googleApiKey: string;
  googleClientEmail: string;
  googleSpreadsheetId: string;
  googleWorksheetName: string;
}

export const getWorksheetByName = async (
  options: SpreadsheetOptions,
  log: (message: string) => void,
) => {
  const {
    googleApiKey,
    googleClientEmail,
    googleSpreadsheetId,
    googleWorksheetName,
  } = options;
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: googleClientEmail,
    key: Buffer.from(googleApiKey, 'base64').toString(),
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  let spRows: any = null;
  for (let cpt = 1; cpt < 4; cpt++) {
    if (spRows === null) {
      log(`Connecting to spreadsheet: ${cpt}/3`);
      try {
         
        spRows = await getSpreadsheet({
          googleSpreadsheetId,
          log,
          serviceAccountAuth,
          worksheetTitle: googleWorksheetName,
        });
      } catch {
        log('Unable to connect to spreadsheet');
      }
    }
  }

  return spRows;
};
