import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';

const findSheetByTitle = (doc: any, title: string, log: any): any => {
  const { sheetCount } = doc;
  for (let i = 0; i < sheetCount; i++) {
    if (doc.sheetsByIndex[i].title === title) {
      log(
        `Reviewing sheet with title: ${doc.sheetsByIndex[i].title} <- SHEET FOUND`,
      );
      return doc.sheetsByIndex[i];
    }

    log(`Reviewing sheet with title: ${doc.sheetsByIndex[i].title}`);
  }

  return null;
};

const getSpreadsheet = async (
  serviceAccountAuth: JWT,
  googleSpreadsheetId: string,
  worksheetTitle: string,
  log: any,
) => {
  const doc = new GoogleSpreadsheet(googleSpreadsheetId, serviceAccountAuth);
  await doc.loadInfo();
  log(`Loaded spreadsheet: ${doc.title}`);
  const sheet = findSheetByTitle(doc, worksheetTitle, log);
  if (sheet === null) {
    log(
      `Worksheet with title "${worksheetTitle}" not found in spreadsheet "${doc.title}"`,
    );
  }

  return sheet;
};

export const getWorksheetByName = async (
  googleSpreadsheetId: string,
  googleClientEmail: string,
  googleApiKey: string,
  googleWorksheetName: string,
  log: any,
) => {
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: googleClientEmail,
    key: Buffer.from(googleApiKey, 'base64').toString(),
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  let spRows: any = null;
  for (let cpt = 1; cpt < 4; cpt++) {
    if (spRows === null) {
      log(`Connecting to spreadsheet: ${cpt}/3`);
      try {
        // eslint-disable-next-line no-await-in-loop
        spRows = await getSpreadsheet(
          serviceAccountAuth,
          googleSpreadsheetId,
          googleWorksheetName,
          log,
        );
      } catch {
        log('Unable to connect to spreadsheet');
      }
    }
  }

  return spRows;
};
